#Numpy Introdunction

In [1]:
import numpy as np

myarr is a np array. np.int8 means it is size of the number of bits in the list...if it is int8 it means there will be two numbers with size of 4 bits each...It can be changed to int16, int32, int64,...

In [6]:
myarr = np.array([[3, 43, 64, 75]], np.int64) 

In [3]:
myarr

array([ 3, 43, 64], dtype=int8)

In [7]:
myarr[0, 1] #it is for two dimensional array it will provide number at position 0th row and 1th column


43

In [8]:
myarr.shape # it will provide shape or dimensions of the array

(1, 4)

In [9]:
myarr.dtype # it will give which type of the array is


dtype('int64')

In [12]:
myarr[0, 2] = 99 # Used for updatation of the array

In [11]:
myarr

array([[ 3, 99, 64, 75]])

In [13]:
myarr

array([[ 3, 99, 99, 75]])

#Array creation :- coversion from other Python Structures

In [15]:
listarray = np.array([[1, 2, 3], [5, 8, 9], [65, 94, 78]])

In [16]:
listarray

array([[ 1,  2,  3],
       [ 5,  8,  9],
       [65, 94, 78]])

In [17]:
listarray.dtype

dtype('int64')

In [18]:
listarray.shape

(3, 3)

In [19]:
listarray.size

9

In [20]:
listarray[2, 2] = 100

In [21]:
listarray

array([[  1,   2,   3],
       [  5,   8,   9],
       [ 65,  94, 100]])

In [22]:
listarray[1, 1] = 99

In [23]:
listarray

array([[  1,   2,   3],
       [  5,  99,   9],
       [ 65,  94, 100]])

In [24]:
np.array({1, 2, 3}) # here the objects are not efficient when calculating 

array({1, 2, 3}, dtype=object)

#Intrinsic numpy array creation objects

In [26]:
zeros = np.zeros((2, 5)) # it will make an arrat of dimensions 2x5 and fill it with zeros

In [27]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [28]:
zeros.shape

(2, 5)

In [30]:
rng = np.arange(15) #Will provide the range of given size

In [31]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [32]:
rng2 = np.arange(4, 10)

In [33]:
rng2

array([4, 5, 6, 7, 8, 9])

In [34]:
lSpace = np.linspace(1, 5, 12) # So this will provide 12 numbers those will be between 1 to 5 equally lineraly spaced numbers

In [35]:
lSpace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [36]:
emp = np.empty((4, 6)) # it will provide the empty spaces between 4 to 6 so we can use them to assign the values to those spaces

In [37]:
emp

array([[1.3322255e-316, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000,
        0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000,
        0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000,
        0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000,
        0.0000000e+000, 0.0000000e+000]])

In [38]:
emp_like = np.empty_like(lSpace)# it takes an array and make it empty

In [40]:
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [41]:
ide = np.identity(45) # will provide the identity matrix of size 45x45

In [42]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [43]:
ide.shape

(45, 45)

In [49]:
arr2 = np.arange(99)

In [45]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [51]:
arr2 = arr2.reshape(3, 33) # It will reshape the matrix by provide dimensions but the dimensions shoul;d be given so that the multiplication of those two numbers should be the old matrix size

In [50]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [52]:
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [54]:
arr2 = arr2.ravel() # This will make matrix as it was originally

In [55]:
arr2.shape

(99,)

#NumPy Axis

In [57]:
x = [[1, 2, 3], [4, 5, 6], [7, 1, 0]]

In [58]:
arr = np.array(x)

In [59]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [61]:
arr.sum(axis=0) # it will add all the column's number and axis 0 means its like axis X

array([12,  8,  9])

In [62]:
arr.sum(axis = 1)

array([ 6, 15,  8])

In [63]:
arr.T # this makes the transpose of the matrix

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [64]:
arr.flat #This will provide iterator so we can print the whole matrix in form of array

In [65]:
for item in arr.flat: # it will print the matrix
  print(item)


1
2
3
4
5
6
7
1
0


In [66]:
arr.ndim # ndim = number of dimensions

2

In [67]:
arr.size

9

In [68]:
arr.nbytes #Total bytes consumed

72

In [69]:
one = np.array([1,3, 64, 646, 2])

In [70]:
one.argmax() #It provides the index of maximum numbers

3

In [71]:
one.argmin() #It provides the index of minimum numbers

0

In [72]:
one.argsort() # This gives sequence of the indices in sorted manner

array([0, 4, 1, 2, 3])

In [73]:
arr.argmin()

8

In [74]:
arr.argmax()

6

In [75]:
arr.argmax(axis = 0) # it will provide the index numbers of the maximum numbers in the axis 0

array([2, 1, 1])

In [76]:
arr.argmax(axis = 1) # it will provide the index numbers of the maximum numbers in the axis 1

array([2, 2, 0])

In [77]:
arr.argsort(axis = 0) # It provieds the indices if they were used then it will sorted

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]])

In [78]:
arr.argsort(axis = 1)

      #axis = 1 ----->
# array. ([[0, 1, 2],  axis = 0
#        [0, 1, 2],       |
#        [2, 1, 0]])      |
#                         V

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [79]:
arr.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [81]:
arr.reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [82]:
arr2 = np.array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [83]:
arr + arr2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [84]:
arr * arr2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [85]:
np.sqrt(arr) # Will take squre root of the arr matrix

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [86]:
arr.sum()

29

In [87]:
arr.min()

0

In [88]:
arr.max()

7

In [89]:
arr2.sum()

23

In [90]:
arr2.min()

0

In [91]:
arr2.max()

8

**For Finding the elements**

In [92]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [95]:
np.where(arr>5) # Will give the position where the arr number id greater than 5

(array([1, 2]), array([2, 0]))

In [94]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [97]:
type(np.where(arr>5))

tuple

In [98]:
np.count_nonzero(arr) # will provide count of all non zero numbers

8

In [99]:
np.nonzero(arr)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

**Foe checking the space effiency**

In [100]:
import sys

In [101]:
py_ar = [0, 4, 55, 2] #This is a normal array, not a numPy Arrya

In [103]:
np_ar = np.array(py_ar) # Here a NumPy array is created same as py_ar

In [104]:
sys.getsizeof(1) * len(py_ar)

112

In [105]:
np_ar.itemsize * np_ar.size # Here is the difference that NumPy uses very low space as compared to the normal array

32

https://docs.scipy.org/doc/numpy-1.6.0/reference/generated/numpy.ndarray.html

refer this for NumPy attributes