##**Imports**

In [1]:
import pandas as pd
import numpy as np

In [2]:
import os


##**DataSet**

In [3]:
dataset = pd.read_csv('iris.csv') # reading the data and assigning to the dataset

In [4]:
dataset.head()

120    4  setosa  versicolor  virginica
0  6.4  2.8     5.6         2.2          2
1  5.0  2.3     3.3         1.0          1
2  4.9  2.5     4.5         1.7          2
3  4.9  3.1     1.5         0.1          0
4  5.7  3.8     1.7         0.3          0

In [5]:
x = dataset.iloc[:, 1: 5].values # The provided data is encoded in array

In [6]:
x

array([[2.8, 5.6, 2.2, 2. ],
       [2.3, 3.3, 1. , 1. ],
       [2.5, 4.5, 1.7, 2. ],
       [3.1, 1.5, 0.1, 0. ],
       [3.8, 1.7, 0.3, 0. ],
       [3.2, 1.3, 0.2, 0. ],
       [3.4, 1.5, 0.4, 0. ],
       [3.1, 5.1, 2.3, 2. ],
       [3.1, 4.4, 1.4, 1. ],
       [3.7, 1.5, 0.4, 0. ],
       [2.7, 3.9, 1.4, 1. ],
       [3.1, 4.9, 1.5, 1. ],
       [4. , 1.2, 0.2, 0. ],
       [3.9, 1.7, 0.4, 0. ],
       [3.8, 6.7, 2.2, 2. ],
       [3.3, 4.7, 1.6, 1. ],
       [3.2, 5.9, 2.3, 2. ],
       [3. , 6.6, 2.1, 2. ],
       [3.2, 5.3, 2.3, 2. ],
       [4.4, 1.5, 0.4, 0. ],
       [3.3, 5.7, 2.1, 2. ],
       [2.8, 5.6, 2.1, 2. ],
       [3.9, 1.3, 0.4, 0. ],
       [2.6, 5.6, 1.4, 2. ],
       [3. , 5.8, 1.6, 2. ],
       [3.5, 1.5, 0.2, 0. ],
       [2.6, 4. , 1.2, 1. ],
       [3. , 5.1, 1.8, 2. ],
       [3. , 4.5, 1.5, 1. ],
       [3. , 5. , 1.7, 1. ],
       [2.3, 4.4, 1.3, 1. ],
       [2.5, 3. , 1.1, 1. ],
       [3.2, 4.5, 1.5, 1. ],
       [3. , 5.5, 2.1, 2. ],
       [2.8, 4

In [7]:
y = dataset.iloc[:,4].values

In [8]:
y

array([2, 1, 2, 0, 0, 0, 0, 2, 1, 0, 1, 1, 0, 0, 2, 1, 2, 2, 2, 0, 2, 2,
       0, 2, 2, 0, 1, 2, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 0,
       0, 2, 0, 2, 0, 2, 0, 1, 1, 0, 1, 2, 2, 2, 2, 1, 1, 2, 2, 2, 1, 2,
       0, 2, 2, 0, 0, 1, 0, 2, 2, 0, 1, 1, 1, 2, 0, 1, 1, 1, 2, 0, 1, 1,
       1, 0, 2, 1, 0, 0, 2, 0, 0, 2, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       2, 1, 0, 2, 0, 1, 1, 0, 0, 1])

In [9]:
from sklearn.preprocessing import LabelEncoder
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y) # by This the whole data is converted into mathematical data, of the name of the flowers

In [10]:
y

array([2, 1, 2, 0, 0, 0, 0, 2, 1, 0, 1, 1, 0, 0, 2, 1, 2, 2, 2, 0, 2, 2,
       0, 2, 2, 0, 1, 2, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 0,
       0, 2, 0, 2, 0, 2, 0, 1, 1, 0, 1, 2, 2, 2, 2, 1, 1, 2, 2, 2, 1, 2,
       0, 2, 2, 0, 0, 1, 0, 2, 2, 0, 1, 1, 1, 2, 0, 1, 1, 1, 2, 0, 1, 1,
       1, 0, 2, 1, 0, 0, 2, 0, 0, 2, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       2, 1, 0, 2, 0, 1, 1, 0, 0, 1])

##**Modelling :- spliting data in train and test**

In [11]:
 from sklearn.model_selection import train_test_split 
 x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2) # 0.2 means 20 % data is for testing and 80% is for traing the data

##**Logistics Regression**

In [12]:
from sklearn.linear_model import LogisticRegression
logmodel = LogisticRegression()
logmodel.fit(x_train, y_train)

LogisticRegression()

In [13]:
y_pred = logmodel.predict(x_test)

In [14]:
y_pred

array([2, 2, 1, 2, 2, 0, 1, 1, 0, 1, 0, 0, 2, 1, 2, 0, 2, 0, 2, 1, 2, 2,
       0, 0])

In [15]:
y_test

array([2, 2, 1, 2, 2, 0, 1, 1, 0, 1, 0, 0, 2, 1, 2, 0, 2, 0, 2, 1, 2, 2,
       0, 0])

In [16]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[ 8,  0,  0],
       [ 0,  6,  0],
       [ 0,  0, 10]])

As the given matrix, first row means the Actual data of the first category of the flowers,and so on. and the first column means the predicted data of the first category.

In [17]:
#Accuracy can be measured by (10 + 6 + 8) / (Summation of all numbers in matrix)
#i.e. 100 percent
24/24 

1.0

##**K-Nearest Neighbours**

In [18]:
from sklearn.neighbors import KNeighborsClassifier
classifier_knn = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2) #Will chech for 5 neighbors
classifier_knn.fit(x_train, y_train)

KNeighborsClassifier()

In [19]:
y_pred = classifier_knn.predict(x_test)

In [20]:
confusion_matrix(y_test, y_pred)

array([[ 8,  0,  0],
       [ 0,  6,  0],
       [ 0,  0, 10]])

In [21]:
#Accuracy 100%

##**Naive Bayes**

In [22]:
from sklearn.naive_bayes import GaussianNB
classifier_nb = GaussianNB()
classifier_nb.fit(x_train, y_train)

GaussianNB()

In [23]:
y_pred = classifier_nb.predict(x_test)

In [24]:
confusion_matrix(y_test, y_pred)

array([[ 8,  0,  0],
       [ 0,  6,  0],
       [ 0,  0, 10]])

In [25]:
# accuracy is equals to 100%

##**Support Vector Machine**

###Sigmoid Kernel

In [26]:
from sklearn.svm import SVC
classifier_svm_sigmoid = SVC(kernel = 'sigmoid')
classifier_svm_sigmoid.fit(x_train, y_train)

SVC(kernel='sigmoid')

In [27]:
y_pred = classifier_svm_sigmoid.predict(x_test)

In [28]:
confusion_matrix(y_test, y_pred)

array([[ 1,  0,  7],
       [ 4,  0,  2],
       [10,  0,  0]])

In [29]:
#Here models accuracy is decreased that is becomed 16%

###Linear Kernel

In [30]:
from sklearn.svm import SVC
classifier_svm_linear = SVC(kernel = 'linear')
classifier_svm_linear.fit(x_train, y_train)

SVC(kernel='linear')

In [31]:
y_pred = classifier_svm_linear.predict(x_test)

In [32]:
confusion_matrix(y_test, y_pred)

array([[ 8,  0,  0],
       [ 0,  6,  0],
       [ 0,  0, 10]])

In [33]:
# accuracy is equals to 100%

###Radial Basis Function  Kernel

In [34]:
from sklearn.svm import SVC
classifier_svm_rbf = SVC(kernel = 'rbf')
classifier_svm_rbf.fit(x_train, y_train)

SVC()

In [35]:
y_pred = classifier_svm_rbf.predict(x_test)

In [36]:
confusion_matrix(y_test, y_pred)

array([[ 8,  0,  0],
       [ 0,  6,  0],
       [ 0,  0, 10]])

In [37]:
# accuracy is equals to 100%

###**Polynomial Kernel**

In [38]:
from sklearn.svm import SVC
classifier_svm_poly = SVC(kernel = 'poly')
classifier_svm_poly.fit(x_train, y_train)

SVC(kernel='poly')

In [39]:
y_pred = classifier_svm_poly.predict(x_test)

In [40]:
confusion_matrix(y_test, y_pred)

array([[ 8,  0,  0],
       [ 0,  6,  0],
       [ 0,  0, 10]])

In [41]:
# accuracy is equals to 100%

##**Decision Tree Classfier** 

In [42]:
from sklearn.tree import DecisionTreeClassifier
classifier_dtc = DecisionTreeClassifier(criterion = 'entropy') # entropy means impurity in the data set
classifier_dtc.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy')

In [43]:
y_pred  = classifier_dtc.predict(x_test)

In [44]:
confusion_matrix(y_test, y_pred)

array([[ 8,  0,  0],
       [ 0,  6,  0],
       [ 0,  0, 10]])

In [45]:
# accuracy is equals to 100%

##**Random Forest** 

In [46]:
from sklearn.ensemble import RandomForestClassifier
classifier_rf = RandomForestClassifier(n_estimators = 3, criterion = 'entropy')
classifier_rf.fit(x_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=3)

In [47]:
y_pred  = classifier_rf.predict(x_test)

In [48]:
confusion_matrix(y_test, y_pred)

array([[ 8,  0,  0],
       [ 0,  6,  0],
       [ 0,  0, 10]])

In [49]:
# accuracy is equals to 100%